services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel10-app
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data_10:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    container_name: laravel10-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3310:3306"

  nginx:
    image: nginx:alpine
    container_name: laravel10-nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
volumes:
  db_data_10: